### PR TITLE
[WIP] Customize start for Node.js

### LINKED ISSUE #1: Can't find last release in a node.js repo
I'm trying to use releasetool to ship a new version of [nodejs-common](https://github.com/googleapis/nodejs-common/).  Generally we use the last tag with a `v*` to figure out the last release, but it looks like releasetool is having trouble figuring that out:

```sh
beckwith-macbookpro2:nodejs-common beckwith$ releasetool
o/ Hey, beckwith, let's release some stuff!
> Determining basic context.
GitHub Repo: JustinBeckwith/nodejs-common
> Figuring out the package name.
Looks like we're releasing nodejs-common.
> Figuring out what the last release was.
I couldn't figure out the last release for nodejs-common, so I'm assuming this is the first release. Can you tell me which git rev/sha to start the changelog at?
```

How is it trying to find the last release?

### PR DESCRIPTION
**Pull request by theacodes**
Fixes #1 

Example PR: https://github.com/googleapis/nodejs-vision/pull/107

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
Looking great so far.  Left some feedback/questions in https://github.com/googleapis/nodejs-vision/pull/107#pullrequestreview-133375282

**Comment by crwilcox** [comment]
The current release process is to run `repo-tools bump patch|minor|major` 

https://github.com/GoogleCloudPlatform/nodejs-repo-tools/blob/7551ab2aadf2c73553299888a38e2c05c85c79a1/src/cli/commands/bump.js

Basically though you have to rev the version in `package.json` and the dependency version in `samples/package.json`. Then,

```
 rm -f package-lock.json && npm install && npm link
 git add package.json package-lock.json
 cd samples && rm -f package-lock.json && npm link ../ && npm install && cd ..
 git add samples/package.json samples/package-lock.json
 git commit -m "chore: bump version to {VERSION}
```

**Comment by theacodes** [comment]
From https://github.com/googleapis/nodejs-vision/pull/107#discussion_r199280211

> There should be a corresponding change in the `package-lock.json` as well.

> I typically use npm to do the version bump for me, and it takes care of updating both.

```
$ npm version --no-git-tag-version {minor|major|patch|specific version}
```

> We use the no-git-tag as per the release process at go/npm-at-google wherein the release is published when the draft release notes are published.

**Comment by crwilcox** [comment]
@theacodes  yeah. I am 100% against using repo tools for bump. What I pasted is ultimately what repo tools does, which isn't very much tbh.

**Comment by theacodes** [comment]
@crwilcox gotcha, I misunderstood.

**Comment by JustinBeckwith** [comment]
@crwilcox @theacodes should we land this and then make incremental improvements?

**Comment by JustinBeckwith** [comment]
I am cool with a changelog.

**Pull request merged**
