### PR TITLE
Add links to pull requests in release log

### PR DESCRIPTION
**Pull request by busunkim96**
#38 `Some change (#13)` --> `Some change ([#13](https://github.com/owner/repo/pull/13))`

### CODE REVIEW

**Comment by chingor13** [comment]
I think GitHub already links #[PR or issue number] automatically. Example: https://github.com/google/google-auth-library-java/releases/tag/v0.11.0

**Comment by JustinBeckwith** [comment]
It does, but that doesn't work for the generated changlog.md we include in the package ;)

**Comment by chingor13** [comment]
Ah, makes sense

**Comment by JustinBeckwith** [comment]
@busunkim96 🎉congrats on landing the first of many!

**Pull request merged**
